// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmagxllswukffrrxqmto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtYWd4bGxzd3VrZmZycnhxbXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjczOTIsImV4cCI6MjA2MDc0MzM5Mn0.V9hQSyMMBfkpNHns8VGOe1Pm6MWXG1T-jxQyVKatyn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);